const fs = require('fs');
const file = 'js/admin-app.js';
let content = fs.readFileSync(file, 'utf8');

// Map of visible mojibake patterns to correct Spanish text
const textFixes = [
  ['ArtÃ­culo', 'Artículo'],
  ['AÃ±adir', 'Añadir'],
  ['RÃ¡pido', 'Rápido'],
  ['aÃ±adieron', 'añadieron'],
  ['aÃ±adir', 'añadir'],
  ['ConexiÃ³n', 'Conexión'],
  ['SupervisiÃ³n', 'Supervisión'],
  ['TÃ©cnico', 'Técnico'],
  ['tÃ©cnico', 'técnico'],
  ['rechazÃ³', 'rechazó'],
  ['BÃºscalo', 'Búscalo'],
  ['eliminÃ³', 'eliminó'],
  ['encontrÃ³', 'encontró'],
  ['acciÃ³n', 'acción'],
  ['CÃ³digo', 'Código'],
  ['artÃ­culo', 'artículo'],
  ['actualizÃ³', 'actualizó'],
  ['DirecciÃ³n', 'Dirección'],
  ['botÃ³n', 'botón'],
  ['animaciÃ³n', 'animación'],
  ['Ã©xito', 'éxito'],
  ['ESTÃÂS', 'ESTÁS'],
  ['CATEGORÃA', 'CATEGORÍA'],
  ['GestiÃ³n', 'Gestión'],
  ['gestiÃ³n', 'gestión'],
  ['configuraciÃ³n', 'configuración'],
  ['ConfiguraciÃ³n', 'Configuración'],
  ['CumpleaÃ±os', 'Cumpleaños'],
  ['cumpleaÃ±os', 'cumpleaños'],
  ['telÃ©fono', 'teléfono'],
  ['opciÃ³n', 'opción'],
  ['OpciÃ³n', 'Opción'],
  ['notificaciÃ³n', 'notificación'],
  ['NotificaciÃ³n', 'Notificación'],
  ['selecciÃ³n', 'selección'],
  ['SelecciÃ³n', 'Selección'],
  ['sesiÃ³n', 'sesión'],
  ['SesiÃ³n', 'Sesión'],
  ['secciÃ³n', 'sección'],
  ['SecciÃ³n', 'Sección'],
  ['informaciÃ³n', 'información'],
  ['InformaciÃ³n', 'Información'],
  ['creaciÃ³n', 'creación'],
  ['CreaciÃ³n', 'Creación'],
  ['ediciÃ³n', 'edición'],
  ['EdiciÃ³n', 'Edición'],
  ['eliminaciÃ³n', 'eliminación'],
  ['EliminaciÃ³n', 'Eliminación'],
  ['publicaciÃ³n', 'publicación'],
  ['PublicaciÃ³n', 'Publicación'],
  ['comunicaciÃ³n', 'comunicación'],
  ['ComunicaciÃ³n', 'Comunicación'],
  ['presentaciÃ³n', 'presentación'],
  ['PresentaciÃ³n', 'Presentación'],
  ['verificaciÃ³n', 'verificación'],
  ['VerificaciÃ³n', 'Verificación'],
  ['autorizaciÃ³n', 'autorización'],
  ['AutorizaciÃ³n', 'Autorización'],
  ['cancelaciÃ³n', 'cancelación'],
  ['CancelaciÃ³n', 'Cancelación'],
  ['operaciÃ³n', 'operación'],
  ['OperaciÃ³n', 'Operación'],
  ['posiciÃ³n', 'posición'],
  ['PosiciÃ³n', 'Posición'],
  ['restricciÃ³n', 'restricción'],
  ['RestricciÃ³n', 'Restricción'],
  ['descripciÃ³n', 'descripción'],
  ['DescripciÃ³n', 'Descripción'],
  ['transacciÃ³n', 'transacción'],
  ['TransacciÃ³n', 'Transacción'],
  ['asignaciÃ³n', 'asignación'],
  ['AsignaciÃ³n', 'Asignación'],
  ['revisiÃ³n', 'revisión'],
  ['RevisiÃ³n', 'Revisión'],
  ['evaluaciÃ³n', 'evaluación'],
  ['EvaluaciÃ³n', 'Evaluación'],
  ['administraciÃ³n', 'administración'],
  ['AdministraciÃ³n', 'Administración'],
  ['organizaciÃ³n', 'organización'],
  ['OrganizaciÃ³n', 'Organización'],
  ['soluciÃ³n', 'solución'],
  ['SoluciÃ³n', 'Solución'],
  ['direcciÃ³n', 'dirección'],
  ['categorizaciÃ³n', 'categorización'],
  ['autenticaciÃ³n', 'autenticación'],
  ['fijaciÃ³n', 'fijación'],
  ['ubicaciÃ³n', 'ubicación'],
  ['UbicaciÃ³n', 'Ubicación'],
  ['conexiÃ³n', 'conexión'],
  ['ComparaciÃ³n', 'Comparación'],
  ['poblaciÃ³n', 'población'],
  ['ejecuciÃ³n', 'ejecución'],
  ['EjecuciÃ³n', 'Ejecución'],
  ['generaciÃ³n', 'generación'],
  ['GeneraciÃ³n', 'Generación'],
  ['validaciÃ³n', 'validación'],
  ['ValidaciÃ³n', 'Validación'],
  ['integraciÃ³n', 'integración'],
  ['IntegraciÃ³n', 'Integración'],
  ['producciÃ³n', 'producción'],
  ['ProducciÃ³n', 'Producción'],
  ['protecciÃ³n', 'protección'],
  ['ProtecciÃ³n', 'Protección'],
  // standalone accented chars in context
  ['aÃºn', 'aún'],
  ['aÃºn', 'aún'],
  ['todavÃ­a', 'todavía'],
  ['tambiÃ©n', 'también'],
  ['TambiÃ©n', 'También'],
  ['despuÃ©s', 'después'],
  ['DespuÃ©s', 'Después'],
  ['tÃ©cnicos', 'técnicos'],
  ['mÃ³dulo', 'módulo'],
  ['MÃ³dulo', 'Módulo'],
  ['pÃ¡gina', 'página'],
  ['pÃ¡ginas', 'páginas'],
  ['PÃ¡gina', 'Página'],
  ['perÃ­odo', 'período'],
  ['anÃ¡lisis', 'análisis'],
  ['AnÃ¡lisis', 'Análisis'],
  ['nÃºmero', 'número'],
  ['nÃºmeros', 'números'],
  ['NÃºmero', 'Número'],
  ['Ã³ptimo', 'óptimo'],
  ['Ã³ptima', 'óptima'],
  ['fÃ¡cil', 'fácil'],
  ['difÃ­cil', 'difícil'],
  ['Ã¡rea', 'área'],
  ['Ã¡reas', 'áreas'],
  ['Ã©xito', 'éxito'],
  ['Ã©lite', 'élite'],
  ['Ã­ndice', 'índice'],
  ['Ã³rgano', 'órgano'],
  ['Ã³rdenes', 'órdenes'],
  ['Ã³ptimas', 'óptimas'],
  ['Ã¼ltimo', 'último'],
  ['Ã¼ltima', 'última'],
  ['Ã¼ltimos', 'últimos'],
  ['Ã¼ltimas', 'últimas'],
  ['Ãºnico', 'único'],
  ['Ãºnica', 'única'],
  ['Ãºnicos', 'únicos'],
  ['Ãºnicas', 'únicas'],
  ['convocatorÃ­a', 'convocatoria'],
  ['categorÃ­a', 'categoría'],
  ['categorizaciÃ³n', 'categorización'],
  ['compaÃ±Ã­a', 'compañía'],
  ['compaÃ±Ã­as', 'compañías'],
  ['espaÃ±ol', 'español'],
  ['EspaÃ±ol', 'Español'],
  ['tamaÃ±o', 'tamaño'],
  ['daÃ±o', 'daño'],
  ['daÃ±os', 'daños'],
  // Ã¢â€â‚¬Ã¢â€â‚¬ is the em-dash comment pattern (— —), fine to clean up
  ['Ã¢â€â‚¬Ã¢â€â‚¬ ', '── '],
  [' Ã¢â€â‚¬Ã¢â€â‚¬', ' ──'],
];

for (const [bad, good] of textFixes) {
  content = content.split(bad).join(good);
}

fs.writeFileSync(file, content, 'utf8');
console.log('Fixed all Spanish encoding in admin-app.js');
