const fs = require('fs');
let code = fs.readFileSync('server.js', 'utf8');

const targetStr = `            const cli = dbData.Clientes_Maestro.map(item => {
                // Remove dynamic properties generated by the frontend so Supabase doesn't complain
                const { proyectos, estado_format, total_amount, balance_amount, pipeline_nombre, total_llamadas, ...rest } = item;
                const mapped = {
                    id:                 item.id,
                    nombres:            item.nombres            || null,
                    apellidos:          item.apellidos          || null,
                    telefono:           item.telefono           || null,
                    email:              item.email              || null,
                    direccion:          item.direccion          || null,
                    notas:              item.notas              || null, 
                    fecha:              item.fecha              || null, 
                    archivos_adjuntos:  item.archivos_adjuntos  || null,
                    // ── ORIGEN (Call Center / Vendedor) ──
                    origen_tipo:              item.origen_tipo              || null,
                    origen_nombre:            item.origen_nombre            || null,
                    origen_id:                item.origen_id                || item.creador_id || null,
                    vendedor_asignado_id:     item.vendedor_asignado_id     || item.responsable_id || null,
                    vendedor_asignado_nombre: item.vendedor_asignado_nombre || null,
                    // ── NUEVAS COLUMNAS (Módulo Clientes v2) ──
                    departamento:       item.departamento       || null,
                    adjunto_id_url:     item.adjunto_id_url     || null,
                    adjunto_bill_url:   item.adjunto_bill_url   || null,
                    adjunto_seguro_url: item.adjunto_seguro_url || null,
                    macro_estado:       item.macro_estado       || null,
                    departamentos_activos: item.departamentos_activos || [],
                    fecha_inicio:       item.fecha_inicio       || null,
                    google_place_id:    item.google_place_id    || null,
                };
                // <i class="fa-solid fa-triangle-exclamation text-orange-500"></i> CRITICAL: Only include adjuntos_oficina and contrato_water_url if they
                // have a real value in the LOCAL cache. If they are null/empty locally, we
                // skip them (undefined) so Supabase does NOT overwrite values previously
                // written directly by the server (race condition prevention).
                if (item.adjuntos_oficina && !Array.isArray(item.adjuntos_oficina) && Object.keys(item.adjuntos_oficina).length > 0) {
                    mapped.adjuntos_oficina = item.adjuntos_oficina;
                }
                if (item.contrato_water_url) {
                    mapped.contrato_water_url = item.contrato_water_url;
                } else if (item.adjuntos_oficina?.contrato_url) {
                    mapped.contrato_water_url = item.adjuntos_oficina.contrato_url;
                }
                if (item.credit_app_url) {
                    mapped.credit_app_url = item.credit_app_url;
                }
                if (item.historial_llamadas) {
                    mapped.historial_llamadas = item.historial_llamadas;
                }
                return mapped;
            });
            syncTasks.push(supabase.from('clientes_maestro').upsert(cli, { onConflict: 'id' }));`;

const targetRegex = new RegExp(targetStr.replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replace(/\s+/g, '\\s*'));

const replacementStr = `            // Pre-fetch existing clients to merge server-side background data safely (like grabacion_url)
            const clientIds = dbData.Clientes_Maestro.map(c => c.id);
            const { data: existingClients } = await supabase.from('clientes_maestro').select('id, historial_llamadas').in('id', clientIds);
            const existingMap = {};
            if (existingClients) {
                existingClients.forEach(c => existingMap[c.id] = c);
            }

            const cli = dbData.Clientes_Maestro.map(item => {
                const { proyectos, estado_format, total_amount, balance_amount, pipeline_nombre, total_llamadas, ...rest } = item;
                const mapped = {
                    id:                 item.id,
                    nombres:            item.nombres            || null,
                    apellidos:          item.apellidos          || null,
                    telefono:           item.telefono           || null,
                    email:              item.email              || null,
                    direccion:          item.direccion          || null,
                    notas:              item.notas              || null, 
                    fecha:              item.fecha              || null, 
                    archivos_adjuntos:  item.archivos_adjuntos  || null,
                    origen_tipo:              item.origen_tipo              || null,
                    origen_nombre:            item.origen_nombre            || null,
                    origen_id:                item.origen_id                || item.creador_id || null,
                    vendedor_asignado_id:     item.vendedor_asignado_id     || item.responsable_id || null,
                    vendedor_asignado_nombre: item.vendedor_asignado_nombre || null,
                    departamento:       item.departamento       || null,
                    adjunto_id_url:     item.adjunto_id_url     || null,
                    adjunto_bill_url:   item.adjunto_bill_url   || null,
                    adjunto_seguro_url: item.adjunto_seguro_url || null,
                    macro_estado:       item.macro_estado       || null,
                    departamentos_activos: item.departamentos_activos || [],
                    fecha_inicio:       item.fecha_inicio       || null,
                    google_place_id:    item.google_place_id    || null,
                };
                
                if (item.adjuntos_oficina && !Array.isArray(item.adjuntos_oficina) && Object.keys(item.adjuntos_oficina).length > 0) {
                    mapped.adjuntos_oficina = item.adjuntos_oficina;
                }
                if (item.contrato_water_url) {
                    mapped.contrato_water_url = item.contrato_water_url;
                } else if (item.adjuntos_oficina?.contrato_url) {
                    mapped.contrato_water_url = item.adjuntos_oficina.contrato_url;
                }
                if (item.credit_app_url) {
                    mapped.credit_app_url = item.credit_app_url;
                }
                
                if (item.historial_llamadas) {
                    const existing = existingMap[item.id];
                    if (existing && existing.historial_llamadas) {
                        // Merge calls to prevent overwriting webhooks
                        const callMap = {};
                        // 1. Load server calls (source of truth for recordings and new calls)
                        existing.historial_llamadas.forEach(c => {
                            if (c.call_id) callMap[c.call_id] = { ...c };
                        });
                        // 2. Overlay client calls (source of truth for proyecto_id modifications)
                        item.historial_llamadas.forEach(c => {
                            if (c.call_id) {
                                if (callMap[c.call_id]) {
                                    callMap[c.call_id].proyecto_id = c.proyecto_id || callMap[c.call_id].proyecto_id;
                                    // Do NOT overwrite grabacion_url if server has it
                                    if (!callMap[c.call_id].grabacion_url && c.grabacion_url) {
                                        callMap[c.call_id].grabacion_url = c.grabacion_url;
                                    }
                                } else {
                                    callMap[c.call_id] = { ...c };
                                }
                            }
                        });
                        // Sort by date ascending (or keeping them as is, usually webhooks just push)
                        mapped.historial_llamadas = Object.values(callMap).sort((a,b) => new Date(a.fecha) - new Date(b.fecha));
                    } else {
                        mapped.historial_llamadas = item.historial_llamadas;
                    }
                }
                return mapped;
            });
            syncTasks.push(supabase.from('clientes_maestro').upsert(cli, { onConflict: 'id' }));`;

if (targetRegex.test(code)) {
    code = code.replace(targetRegex, replacementStr);
    console.log("Replaced successfully");
} else {
    // String match fallback with robust spacing normalization
    let nOld = targetStr.replace(/\s+/g, '');
    let nCode = code.replace(/\s+/g, '');
    if (nCode.includes(nOld)) {
        console.log("Matched without spaces, but need exact replacement. Try indexof...");
        // Can't replace easily if whitespace differs, regex is best.
    }
    console.log("Regex failed to match. Using string fallback.");
    code = code.replace(targetStr, replacementStr);
}

fs.writeFileSync('server.js', code, 'utf8');
