const products = [
  // LINEA RENEW ECONÓMICA
  {
    codigo: "E-301",
    nombre: "RENEW 3 PASOS S/CARCASA",
    categoria: "LINEA RENEW ECONÓMICA",
    medida: "10 X 44",
    boton: "3B",
    color: "NEGRO",
    precio_minimo: 2500,
    precio_maximo: 4000,
    precio_junior: 2000,
    precio_subvende: 2500,
    precio_vendedor: 1900,
    precio_analista: 1750,
    precio_oficina: 1600,
    solo_equipo_grande: 1600
  },
  {
    codigo: "E-302",
    nombre: "RENEW 4 PASOS S/CARCASA",
    categoria: "LINEA RENEW ECONÓMICA",
    medida: "9 X 48",
    boton: "3B",
    color: "NEGRO",
    precio_minimo: 2500,
    precio_maximo: 4500,
    precio_junior: 2200,
    precio_subvende: 2700,
    precio_vendedor: 2000,
    precio_analista: 1900,
    precio_oficina: 1700,
    solo_equipo_grande: 1700
  },
  {
    codigo: "E-303",
    nombre: "RENEW 4 PASOS S/CARCASA",
    categoria: "LINEA RENEW ECONÓMICA",
    medida: "10 X 54",
    boton: "3B",
    color: "NEGRO",
    precio_minimo: 2500,
    precio_maximo: 5000,
    precio_junior: 2350,
    precio_subvende: 2900,
    precio_vendedor: 2200,
    precio_analista: 2100,
    precio_oficina: 1900,
    solo_equipo_grande: 1900
  },
  {
    codigo: "E-P01",
    nombre: "POZO BASICO 10X54 S/CARCASA",
    categoria: "LINEA RENEW ECONÓMICA",
    medida: "10 X 54",
    boton: "3B",
    color: "NEGRO",
    precio_minimo: 0,
    precio_maximo: 6500,
    precio_junior: 3800,
    precio_subvende: 4300,
    precio_vendedor: 3500,
    precio_analista: 3300,
    precio_oficina: 3000,
    solo_equipo_grande: 0
  },
  {
    codigo: "E-P02",
    nombre: "POZO BASICO 13X54 S/CARCASA",
    categoria: "LINEA RENEW ECONÓMICA",
    medida: "13 X 54",
    boton: "3B",
    color: "NEGRO",
    precio_minimo: 0,
    precio_maximo: 6500,
    precio_junior: 4100,
    precio_subvende: 4600,
    precio_vendedor: 3700,
    precio_analista: 3500,
    precio_oficina: 3200,
    solo_equipo_grande: 0
  },
  {
    codigo: "E-PF1",
    nombre: "POZO FULL 10X54 S/CARCASA",
    categoria: "LINEA RENEW ECONÓMICA",
    medida: "10 X 54",
    boton: "3B",
    color: "NEGRO",
    precio_minimo: 0,
    precio_maximo: 6500,
    precio_junior: 4300,
    precio_subvende: 4800,
    precio_vendedor: 4000,
    precio_analista: 3650,
    precio_oficina: 3300,
    solo_equipo_grande: 0
  },
  {
    codigo: "E-PF2",
    nombre: "POZO FULL 13X54 S/CARCASA",
    categoria: "LINEA RENEW ECONÓMICA",
    medida: "13 X 54",
    boton: "3B",
    color: "NEGRO",
    precio_minimo: 0,
    precio_maximo: 6500,
    precio_junior: 4500,
    precio_subvende: 5100,
    precio_vendedor: 4200,
    precio_analista: 3800,
    precio_oficina: 3500,
    solo_equipo_grande: 0
  },

  // LINEA RENEW CLÁSICA
  {
    codigo: "C-A04",
    nombre: "RENEW APTO (4 PASOS) PLASTIC",
    categoria: "LINEA RENEW CLÁSICA",
    medida: "ESTÁNDAR",
    boton: "5B",
    color: "GRIS",
    precio_minimo: 4000,
    precio_maximo: 6000,
    precio_junior: 3000,
    precio_subvende: 3600,
    precio_vendedor: 2800,
    precio_analista: 2400,
    precio_oficina: 2300,
    solo_equipo_grande: 2200
  },
  {
    codigo: "C-M04",
    nombre: "RENEW MINI (4 PASOS)",
    categoria: "LINEA RENEW CLÁSICA",
    medida: "10 X 44",
    boton: "3B",
    color: "NEGRO/GRI/BEI",
    precio_minimo: 3500,
    precio_maximo: 5000,
    precio_junior: 3200,
    precio_subvende: 3800,
    precio_vendedor: 2900,
    precio_analista: 2500,
    precio_oficina: 2200,
    solo_equipo_grande: 2100
  },
  {
    codigo: "C-S04",
    nombre: "RENEW SMALL (4 PASOS) PLASTIC",
    categoria: "LINEA RENEW CLÁSICA",
    medida: "9 X 48",
    boton: "5B",
    color: "BEIGE/GRIS",
    precio_minimo: 4000,
    precio_maximo: 6500,
    precio_junior: 3300,
    precio_subvende: 3900,
    precio_vendedor: 3000,
    precio_analista: 2650,
    precio_oficina: 2300,
    solo_equipo_grande: 2300
  },
  {
    codigo: "C-C05",
    nombre: "RENEW CITY (5 PASOS) PLASTIC",
    categoria: "LINEA RENEW CLÁSICA",
    medida: "10 X 54",
    boton: "5B",
    color: "PLASTICO",
    precio_minimo: 5000,
    precio_maximo: 8500,
    precio_junior: 3500,
    precio_subvende: 4100,
    precio_vendedor: 3300,
    precio_analista: 2900,
    precio_oficina: 2500,
    solo_equipo_grande: 2700
  },
  {
    codigo: "C-C06",
    nombre: "RENEW CITY (6 PASOS) METAL",
    categoria: "LINEA RENEW CLÁSICA",
    medida: "10 X 54",
    boton: "5B",
    color: "METAL",
    precio_minimo: 6000,
    precio_maximo: 9000,
    precio_junior: 3700,
    precio_subvende: 4300,
    precio_vendedor: 3500,
    precio_analista: 3000,
    precio_oficina: 2700,
    solo_equipo_grande: 2900
  },
  {
    codigo: "C-D08",
    nombre: "RENEW DUO (8 PASOS) METAL",
    categoria: "LINEA RENEW CLÁSICA",
    medida: "10 X 54",
    boton: "5B",
    color: "METAL",
    precio_minimo: 7000,
    precio_maximo: 10000,
    precio_junior: 4400,
    precio_subvende: 5100,
    precio_vendedor: 4000,
    precio_analista: 3800,
    precio_oficina: 3600,
    solo_equipo_grande: 3400
  },
  {
    codigo: "C-P06",
    nombre: "RENEW PLUS (6 PASOS) PLASTIC",
    categoria: "LINEA RENEW CLÁSICA",
    medida: "13 X 54",
    boton: "5B",
    color: "BEIGE",
    precio_minimo: 6500,
    precio_maximo: 9500,
    precio_junior: 4000,
    precio_subvende: 4700,
    precio_vendedor: 3600,
    precio_analista: 3300,
    precio_oficina: 3000,
    solo_equipo_grande: 3200
  },

  // LINEA RENEW POZO
  {
    codigo: "P-01",
    nombre: "POZO RENEW ( 2 T )",
    categoria: "LINEA RENEW POZO",
    descripcion: "2 TANQUES + BIG BLUE + ROSKU + POTE SAL + RO",
    medida: "10 X 54",
    boton: "GOLD",
    color: "NEG/GRI/BEIG",
    precio_minimo: 7000,
    precio_maximo: 12000,
    precio_junior: 5300,
    precio_subvende: 6000,
    precio_vendedor: 5000,
    precio_analista: 4500,
    precio_oficina: 4200,
    solo_equipo_grande: 0
  },
  {
    codigo: "P-02",
    nombre: "POZO RENEW PLUS 13 (2 T )",
    categoria: "LINEA RENEW POZO",
    descripcion: "2 TANQUES + BIG BLUE + ROSKU + POTE SAL + RO",
    medida: "13 X 54",
    boton: "GOLD",
    color: "BEIGE",
    precio_minimo: 7500,
    precio_maximo: 12000,
    precio_junior: 5500,
    precio_subvende: 6300,
    precio_vendedor: 5300,
    precio_analista: 5000,
    precio_oficina: 4500,
    solo_equipo_grande: 0
  },
  {
    codigo: "P-03",
    nombre: "POZO RENEW PLUS + 10 (3 T)",
    categoria: "LINEA RENEW POZO",
    descripcion: "3 TANQUES + BIG BLUE + ROSKU + POTE DE SAL + RO",
    medida: "10 X 54",
    boton: "GOLD",
    color: "NEG/GRI/BEIG",
    precio_minimo: 8000,
    precio_maximo: 12000,
    precio_junior: 6000,
    precio_subvende: 6800,
    precio_vendedor: 5600,
    precio_analista: 5400,
    precio_oficina: 4700,
    solo_equipo_grande: 0
  },
  {
    codigo: "P-04",
    nombre: "POZO RENEW PLUS + 13 (3 T)",
    categoria: "LINEA RENEW POZO",
    descripcion: "3 TANQUES + BIG BLUE + ROSKU + POTE DE SAL + RO",
    medida: "13 X 54",
    boton: "GOLD",
    color: "BEIGE",
    precio_minimo: 8000,
    precio_maximo: 13000,
    precio_junior: 6500,
    precio_subvende: 7200,
    precio_vendedor: 6000,
    precio_analista: 5600,
    precio_oficina: 5000,
    solo_equipo_grande: 0
  },
  {
    codigo: "P-05",
    nombre: "POZO RENEW PREMIUM 10 (2 T)",
    categoria: "LINEA RENEW POZO",
    descripcion: "2 TANQUES + BIG BLUE + ROSKU + POTE SAL + CLORINADOR + TANQUE RETENCION + RO UV",
    medida: "10 X 54",
    boton: "GOLD",
    color: "NEG/GRI/BEIG",
    precio_minimo: 9000,
    precio_maximo: 15000,
    precio_junior: 7000,
    precio_subvende: 7700,
    precio_vendedor: 6500,
    precio_analista: 6200,
    precio_oficina: 5600,
    solo_equipo_grande: 0
  },
  {
    codigo: "P-06",
    nombre: "POZO RENEW PREMIUM 13 (2T)",
    categoria: "LINEA RENEW POZO",
    descripcion: "2 TANQUES + BIG BLUE + ROSKU + POTE SAL + CLORINADOR + TANQUE RETENCION + RO UV",
    medida: "13 X 54",
    boton: "GOLD",
    color: "BEIGE",
    precio_minimo: 9000,
    precio_maximo: 15000,
    precio_junior: 7300,
    precio_subvende: 8000,
    precio_vendedor: 6900,
    precio_analista: 6600,
    precio_oficina: 6000,
    solo_equipo_grande: 0
  },
  {
    codigo: "P-07",
    nombre: "POZO RENEW PREMIUM + PLUS (3T)",
    categoria: "LINEA RENEW POZO",
    descripcion: "3 TANQUES + BIG BLUE + ROSKU + POTE SAL + CLORINADOR + TANQUE RETENCION + RO UV + AIRADOR",
    medida: "13 X 54",
    boton: "GOLD",
    color: "BEIGE",
    precio_minimo: 9500,
    precio_maximo: 15000,
    precio_junior: 7500,
    precio_subvende: 8300,
    precio_vendedor: 7300,
    precio_analista: 7000,
    precio_oficina: 6500,
    solo_equipo_grande: 0
  },

  // LINEA RENEW RO
  {
    codigo: "RO-5",
    nombre: "RO RENEW 5 ETAPAS BASICO",
    categoria: "LINEA RENEW RO",
    medida: "N/A",
    boton: "N/A",
    color: "BLANCO",
    precio_minimo: 2000,
    precio_maximo: 3500,
    precio_junior: 1000,
    precio_subvende: 1500,
    precio_vendedor: 900,
    precio_analista: 700,
    precio_oficina: 600,
    solo_equipo_grande: 500
  },
  {
    codigo: "RO-6",
    nombre: "RO RENEW 6 ETAPAS ALKALINO",
    categoria: "LINEA RENEW RO",
    medida: "N/A",
    boton: "N/A",
    color: "BLANCO",
    precio_minimo: 2000,
    precio_maximo: 3500,
    precio_junior: 1150,
    precio_subvende: 1600,
    precio_vendedor: 1000,
    precio_analista: 900,
    precio_oficina: 700,
    solo_equipo_grande: 600
  },
  {
    codigo: "RO-7",
    nombre: "RO RENEW PRO 7 ETAPAS UV",
    categoria: "LINEA RENEW RO",
    medida: "N/A",
    boton: "N/A",
    color: "BLANCO",
    precio_minimo: 2000,
    precio_maximo: 4000,
    precio_junior: 1300,
    precio_subvende: 1700,
    precio_vendedor: 1200,
    precio_analista: 1100,
    precio_oficina: 1000,
    solo_equipo_grande: 800
  },
  {
    codigo: "RO-CO",
    nombre: "RO RENEW COMERCIAL",
    categoria: "LINEA RENEW RO",
    medida: "COMERCIAL",
    boton: "N/A",
    color: "METAL",
    precio_minimo: 4500,
    precio_maximo: 7000,
    precio_junior: 3000,
    precio_subvende: 3800,
    precio_vendedor: 2500,
    precio_analista: 2300,
    precio_oficina: 1600,
    solo_equipo_grande: 1200
  }
];

const API_URL = 'http://localhost:3010/api/upsert';

async function inject() {
    console.log(`Injecting ${products.length} products with standardized keys...`);

    const records = products.map(p => ({
        ...p,
        id: `wp_v2_${p.codigo.toLowerCase().replace(/[^a-z0-9]/g, '_')}`,
        es_activo: true,
        sede: 'todas',
        precio_full: p.precio_vendedor
    }));

    try {
        const response = await fetch(API_URL, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                table: 'water_productos',
                records: records
            })
        });

        const result = await response.json();
        console.log("Success! Data injected correctly with precio_subvende.");
        console.log("Server response:", result);
    } catch (err) {
        console.error("Error connecting to API:", err.message);
    }
}

inject();
